DROP TABLE IF EXISTS Rentals0;
DROP TABLE IF EXISTS Rentals3;
DROP TABLE IF EXISTS Rentals2;
DROP TABLE IF EXISTS Rentals1;

CREATE TABLE Rentals1 (
       HZ INTEGER NOT NULL, 
       HC VARCHAR(50) NOT NULL,
       PRIMARY KEY (HZ)
);

CREATE TABLE Rentals2 (
       HID INTEGER NOT NULL, 
       HS VARCHAR(50) NOT NULL,
       HZ INTEGER NOT NULL, 
       PRIMARY KEY (HID),
       FOREIGN KEY (HZ) REFERENCES Rentals1 (HZ)
);

CREATE TABLE Rentals3 (
       PID INTEGER NOT NULL,
       PN VARCHAR(50) NOT NULL, 
       PRIMARY KEY (PID)
);

CREATE TABLE Rentals0 (
       PID INTEGER NOT NULL,
       HID INTEGER NOT NULL, 
       S INTEGER NOT NULL, 
       PRIMARY KEY (PID, HID),
       FOREIGN KEY (HID) REFERENCES Rentals2 (HID),
       FOREIGN KEY (PID) REFERENCES Rentals3 (PID)
);


INSERT INTO Rentals1 
SELECT DISTINCT HZ, HC 
FROM Rentals;

INSERT INTO Rentals2
SELECT DISTINCT HID, HS, HZ 
FROM Rentals;

INSERT INTO Rentals3
SELECT DISTINCT PID, PN
FROM Rentals;

INSERT INTO Rentals0
SELECT DISTINCT PID, HID, S 
FROM Rentals;

DROP TABLE IF EXISTS Boats0;
DROP TABLE IF EXISTS Boats1;

CREATE TABLE Boats1 (
	Z INTEGER, 
	T VARCHAR(50), 
	PRIMARY KEY (Z)
);

CREATE TABLE Boats0 (
	BL CHAR(2), 
	BNo INTEGER, 
	Z INTEGER, 
	BN VARCHAR(50), 
	SSN CHAR(10),
	PRIMARY KEY (BL, BNo),
	UNIQUE (Z, BNo),
	FOREIGN KEY (Z) REFERENCES Boats1 (Z)
);

INSERT INTO Boats1 
SELECT DISTINCT Z, T 
FROM Boats;

INSERT INTO Boats0 
SELECT DISTINCT BL, BNo, Z, BN, SSN 
FROM Boats;
